#!/bin/bash
set -eu -o pipefail
IFS=$'\n'

for file in $(find include -name '*.c*' -o -name '*.h*' -printf '%P\n'); do
	guard=$(tr '[a-z/.]' '[A-Z__]' <<<"lib${file}")
	sed -i -r -e "1s/#ifndef .*/#ifndef ${guard}/" \
	          -e "2s/#define .*/#define ${guard}/" include/"${file}"
done
